### ISSUE TITLE
bug (d3-graph-controller): PositionInitializers.Stable rotate graph a little after update

### ISSUE THREAD

**Issue by Akiyamka** [DerYeger/yeger#127]
### Affected Packages

- [x] d3-graph-controller

### Description

When I use `PositionInitializers.Stable` graph rotating a little bit after each update

### Reproduction

```ts
import { defineGraphConfig, PositionInitializers } from "d3-graph-controller";

export const config = (oldGraph?: Graph<ReatomEntity, EntityNode, EntityLink>) =>
  defineGraphConfig<ReatomEntity, EntityNode, EntityLink>({
    nodeRadius: (node: EntityNode) => 32,
    positionInitializer: oldGraph
      ? PositionInitializers.Stable(oldGraph)
      : PositionInitializers.Centered,
  });
```
https://codesandbox.io/p/sandbox/reatom-reactivity-rotate-bug-4645jr?file=%2Fsrc%2Fmain.tsx

### Additional context

Perhaps I am doing something wrong, but I have not found any mention of this type of positioning in the documentation.

[I used this code as example](https://github.com/DerYeger/yeger/blob/da0aa0cbf427697b82b87f566bb4fc8adee5db62/apps/apollo/components/ModelGraph.vue) for archive stable positioning between updates

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Yes, `PositionInitializer.Stable` is not yet documented.

An example usage can be seen here https://github.com/DerYeger/yeger/blob/47d61b8a72939de5ee51f16e27e5098950499b32/apps/formi/components/ModelGraph.vue#L39.

In short, the initializer has to be created by passing an existing graph.
It then matches corresponding nodes by their ids and uses existing position values.

I guess editor didn't report the type issue here.
Unlike the other initializers, `PositionInitializer.Stable` is a function that returns the actual initializer.

**Comment by DerYeger** [comment]
I missed the edit of the issue, it's usually better to create a new issue.

Regarding the rotation, this is caused by the simulation being "reheated" (as d3 calls it) and a new node affecting the position of the existing nodes.
You can configure the [`initialize` alpha](https://graph-controller.yeger.eu/config/#alphas) to reduce the rotation.
