### ISSUE TITLE
What types are supported 

### ISSUE THREAD

**Issue by Today919** [DerYeger/yeger#128]
### Affected Packages

- [ ] @yeger/eslint-config
- [ ] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

What types of files are supported

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by Today919** [comment]
sumit error

**Comment by DerYeger** [comment]
I assume you're referring to the files supported by `@yeger/eslint-config`?

If yes, the following line of the preconfigured `yeger-lint` script includes all supported files.

**https://github.com/DerYeger/yeger/blob/1c885b4b5cae11f2e62ed07b9acae5c2466da53f/packages/eslint-config/src/lint.js#L12**

**Comment by Today919** [comment]
here
 <marmoset-viewer src="/file.mview" responsive />
it's only supported 'mview' ?

**Comment by Today919** [comment]
here
![image](https://user-images.githubusercontent.com/33539464/218427629-9d19e7fd-9f96-4dd4-bb50-bd3c9aff2d68.png)

Is only the "mview" file type supported

**Comment by DerYeger** [comment]
Ah, you're referring to the `vue-marmoset-viewer` components.
Yes, only `mview` is supported, as this library is just a wrapper around the plain JS Marmoset Viewer.

**Comment by Today919** [comment]
Thanks

**Comment by Today919** [comment]
Hello, I have another question. What tools can convert other 3D model files to MVIEW format, such as GLB files
