### ISSUE TITLE
bug: Reactivity not working when using this component in pair with Options api components and Nuxt 2 (Vue 2.7)

### ISSUE THREAD

**Issue by Juanpam** [DerYeger/yeger#129]
### Affected Packages

- [ ] @yeger/eslint-config
- [ ] @yeger/vue-masonry-wall
- [X] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

It seems reactivity is not possible using the following set up:

- Nuxt.js 2 (2.16.0)
- Vue.js 2 (2.7.14)
- @yeger/vue2-masonry-wall (2.3.2)

I tried both with regular component data variables and ref() and reactive() objects to no avail. The rest of the template reacts to changes in the items array but the masonry-wall component does not.

Also, the following warnings are shown upon component creation:

![image](https://user-images.githubusercontent.com/8345151/219247931-65bf29ed-4659-4f58-861b-a9ad1d071758.png)

### Reproduction

Unfortunately at this point I can not post a repo for reproduction but I can share details on my current set up:

- Nuxt.js 2 (2.16.0)
- Vue.js 2 (2.7.14)
- @yeger/vue2-masonry-wall (2.3.2)

I tried both with regular component data variables and ref() and reactive() objects to no avail. The rest of the template reacts to changes in the items array but the masonry-wall component does not.

Also, the following warnings are shown upon component creation:

![image](https://user-images.githubusercontent.com/8345151/219247931-65bf29ed-4659-4f58-861b-a9ad1d071758.png)

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
The last version of this library was published before Nuxt 2 got support for Vue 2.7.14, so I didn't try it myself.
However, since the [plain Vue 2.7 demo](https://vue2-masonry-wall.yeger.eu/) works, I have to assume this is an issue with Nuxt 2.16.

You could try v2.2.1. This was the last release using Vue 2.16 without the composition API.

**Comment by Juanpam** [comment]
@DerYeger I understand. Your suggestion worked like a charm! Thanks a lot. I guess adding this to the README or somewhere where is visible is a good idea.

I'd say once that we port the project to Vue 3 / Nuxt 3 we would use the compatible version from this library as well (V3) so this workaround is really useful as a way of keeping things working while in the middle of updates 👍

**Comment by DerYeger** [comment]
Great! I added a section to the README.

**Comment by MartinX3** [comment]
@DerYeger 
It works with nuxt 2 bridge.
Also now nuxt 2.17 got released. Probably it also works now with 2.17 without bridge.

**Comment by DerYeger** [comment]
> @DerYeger It works with nuxt 2 bridge. Also now nuxt 2.17 got released. Probably it also works now with 2.17 without bridge.

Thanks for the comment! I'll keep this notice in place regardless, in case of an older Vue version being used.

**Comment by MartinX3** [comment]
You're welcome.
Also older vue versions are EoL.
The only supported vue 2 version is 2.7 which goes end of life December 31st, 2023.
https://v2.vuejs.org/lts/

Then also nuxt 2 goes end of life.
If I read their website correctly they also only support the newest 2.x version (now 2.17).
