### ISSUE TITLE
[Question]: How to use `scroll-container` in vue-masonry-wall

### ISSUE THREAD

**Issue by alexisrolland** [DerYeger/yeger#131]
### Description

Could you please provide an example of how to use the property `scroll-container` in vue-masonry-wall and what is the expected behavior?

Right now I am using your plugin to build a nice masonry gallery with infinite scrolling, but every time I add new images to my gallery the scroll bar goes back to the top of the page.

Thanks

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
If you're using the masonry wall component within a container that can scroll, you have to pass a reference of that HTML element as the `scroll-container`.

[The demo](https://vue-masonry-wall.yeger.eu/) has a toggle for that behavior. Enabling the option sets the `overflow-y` CSS prop of the masonry wall's container to `auto` and passes it as the `scroll-container` Vue prop. The prop is required because the scroll position needs to be reset after items have changed.

The demos implementation is included in this repo:
https://github.com/DerYeger/yeger/blob/9a9565119d2ad458260a76e9ba70a9a75d6394f3/docs/vue-masonry-wall-docs/src/app.vue#L16

As the demo also shows, it's possible to add/remove items of the masonry component without the scroll position resetting.

**Comment by alexisrolland** [comment]
Thank you for your prompt answer @DerYeger. Although your explanations are very clear and I looked into the demo code as well. I am failing to implement this properly and the scrollbar is reset at the top of the container every time I add new items.

Would you mind telling me what I'm doing wrong below please?

```html
<template>
  <a-layout class="collection-container">
    <a-layout ref="gallery" class="gallery">
      <masonry-wall
        :items="images"
        :gap="10"
        :column-width="250"
        :scroll-container="scrollContainer"
      >
        <template #default="{ item }">
         [...image...]
        </template>
      </masonry-wall>
    </a-layout>
  </a-layout>
</template>

<script lang="ts">
import { ref } from "vue";

export default class CollectionView extends Vue {
  scrollContainer = ref("gallery");
  // More code...
}
</script>

<style lang="scss" scoped>
.collection-container {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
  overflow: hidden;
  .gallery {
    background: #282828;
    overflow-y: auto;
    padding: 10px;
  }
}
</style>
```

**Comment by DerYeger** [comment]
Is that a correct usage of `ref`?

I think it should be `<a-layout ref="scrollContainer" class="gallery">` and `scrollContainer = ref(null);`.

I'm also not familiar with Vue's class API, so I can't tell you if the script is valid in the first place. Are you sure that refs can be simple properties?

**Comment by alexisrolland** [comment]
I'm also not very sure how to use `ref`... I guess I am mis-using it. I was somehow able to workaround my issue with this `this.scrollContainer = document.querySelector(".gallery");`

```html
<template>
  <a-layout class="collection-container">
    <a-layout class="gallery">
      <masonry-wall
        :items="images"
        :gap="10"
        :column-width="250"
        :scroll-container="scrollContainer"
      >
        <template #default="{ item }">
         [...image...]
        </template>
      </masonry-wall>
    </a-layout>
  </a-layout>
</template>

<script lang="ts">
import { ref } from "vue";

export default class CollectionView extends Vue {
  scrollContainer: any;

  mounted() {
    this.scrollContainer = document.querySelector(".gallery");
  }
  // More code...
}
</script>

<style lang="scss" scoped>
.collection-container {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
  .gallery {
    background: #282828;
    overflow-y: auto;
    padding: 10px;
  }
}
</style>
```

I do have some unexpected behavior though... like newly loaded images are necessarily filling the empty space properly from left to right. Not sure why but I guess it will do for now.

Thank you for your answers!

**Comment by svkmedia** [comment]
If somebody is struggling with scroll-container prop I solved it in Vue SSR like this:

`<masonry-wall
							:items="$page.props.featuresCategories"
							:ssr-columns="1"
							:column-width="300"
							:gap="30"
							v-if="mounted"
							:scroll-container="equipment"
						>`
						
`const equipment = ref(null)
const mounted = ref(false)

onMounted(() => {
	mounted.value = true
})`
