### ISSUE TITLE
feat: Two-way edge

### ISSUE THREAD

**Issue by senicko** [DerYeger/yeger#155]
### Affected Packages

- [ ] @yeger/eslint-config
- [ ] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

This issue affects d3-graph-controler

Allow to define bidirectional (two-way) edges between nodes (do not display arrow, allow to distinguish one-way from two-way edges).

### Additional context

Hello, I am working on an app visualising graph algorithms. This package looks like rescue for me (making graph visualisation from scratch in svg is pure pain). I have one problem though. This package allows to define only directed edges. As you probably know, there are undirected edges (two-way) in graphs too.

Is it possible to add some metadata to edges and do not render arrows for the bidirectional ones? Or maybe there is a way to define bidirectional edge (who knows)?

In case this is impossible may I get some advice on where to look in source to modify this package myself to implement this (Is it even doable)?

Thanks in advance!

### Preferences

- [x] If this is just about adding some logic I can try implementing this myself

**Comment by DerYeger** [comment]
Bi-directional edges are not in the scope of this library, as it focuses on directed graphs in particular.
Feel free to adjust the path calculations and markers.

The padding has to be added to the start as well:

https://github.com/DerYeger/yeger/blob/cc3fb8e26952a6af82e7787ceb9bd22c7b7a350b/packages/d3-graph-controller/src/lib/paths.ts#L97

Add the arrow marker to the start of edges using CSS:

https://github.com/DerYeger/yeger/blob/cc3fb8e26952a6af82e7787ceb9bd22c7b7a350b/packages/d3-graph-controller/src/lib/link.ts#L48

**Comment by DerYeger** [comment]
I'll close this for now, since it's not currently planned. Feel free to reopen the issue if required.
