### ISSUE TITLE
feat: allow consumers to specify a key from which to pull the `key` ID

### ISSUE THREAD

**Issue by FranciscoKloganB** [DerYeger/yeger#157]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

Looking at the source code, it's possible to observe, that we are using `looping` indexes, to generate `keys` for `v-for`, while this appears to work, is usually not recommended to use `index` as IDs.

We could expose an optional prop, which would allow consumers to define a custom key (possibly nested), that should be used from the provided objects.

What do you think?

_ps: I am not a Vue3 expert but I am willing to take on the mantle for this, if required._

### Additional context

The background of why we are now required to include a key in our loops is to provide Vue with an easy way of being able to watch what items in your array (or object) is changing. The default behavior of the v-for is to track things by the index, so the method that the lib utilizes is, perhaps, redundant (although it does resolve lint errors). By tracking the index, Vue watches for changes in the order of items, and will actually patch each item in place when the order changes. The Vue documentation even notes that “this default mode is efficient,” but there are caveats to it and it is not ideal in every use case. Thus, as suggested by the Vue documentation, you should use the unique id of the item. The reason for this is so that Vue can more accurately track changes in the items in your array and update the component state to reflect this, and also to be able to reuse and reorder existing components rather than having to essentially re-render the entire loop.

### Preferences

- [X] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
This is part of v3.5.0, see the updated README for usage of the new `keyMapper` prop.

Thanks for the suggestion!

**Comment by FranciscoKloganB** [comment]
Marvellous! Thank you so much for this awesome lib!
