### ISSUE TITLE
feat: variable width

### ISSUE THREAD

**Issue by gspgsp** [DerYeger/yeger#168]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

This package is too good, if the variable width support will be more perfect

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Great suggestion, thanks!

**Comment by DerYeger** [comment]
v3.7.0 now supports differing column widths. See the README for usage info.
