### ISSUE TITLE
bug: Named export 'defaults' not found.

### ISSUE THREAD

**Issue by Adai-233** [DerYeger/yeger#174]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

Named export 'defaults' not found. The requested module '@yeger/vue-masonry-wall-core' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using: import pkg from '@yeger/vue-masonry-wall-core'; const { defaults: R, useMasonryWall: U } = pkg;

### Reproduction

Nuxt 3.5.3

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
I cannot reproduce this, the plugin works for me.

Please provide an actual reproduction.

**Comment by DerYeger** [comment]
Thank you for the reproduction!

I think it may be dependent on the package manager used.

Please try v4.0.3, it should fix the issue.

**Comment by DerYeger** [comment]
Thanks for reporting the issue! You're welcome!
