### ISSUE TITLE
[Documentation]: How to render dynamic filters SEO-friendly with Nuxt?

### ISSUE THREAD

**Issue by frederikheld** [DerYeger/yeger#176]
### Description

Thanks for your awesome masonry wall plugin! I'm using it with Vue3 and  Nuxt3 and it works like a charm.

My page allows to dynamically filter the items that are displayed in the masonry wall, which works well with this plugin (as opposed to many others). But unfortunately this means that the items are not being rendered in the generate step by Nuxt and thus the source code of the generated website will not contain the text content of these masonry items.

So I tried a different approach with rendering all items all the time and then make the filter add "display: none;" to the item if it is not in the list. The filtering works (except for some tweaking that needs to be dome to remove the grid gap that is still showing for non-existing items). But unfortunately this does not render the text content of the items into the source code of the website.

Is there any way to achieve what I'm looking for?

### Additional context

This is how I filter the items:

```js
const activeFilter = ref('some-string')

const selectedItems = computed(() => {
    return allItems.filter((item) => {
        return !activeFilter.value ||
            item.topics?.includes(activeFilter.value)
    })
})
```
In the template:
```html
                <masonry-wall :items="allItems">
                    <template #default="{ item }">
                        <MyCustomComponent
                            :item="item"
                            :style="(selectedItems.includes(item) ? '' : 'display: none;')"
                        />
                    </template>
                </masonry-wall>
```

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Thanks for the kind words!

There are two main requirements for SSR to work in this scenario:

1. The `ssr-columns` prop has to be set, otherwise the server will never render this component. I suggest `:ssr-columns="1"`, as a single column will probably result in the least CLS (layout shift).
2. The server has to render the component without the filter applied. So if your filter includes all elements by default, you're good to go. If it doesn't, I suggest changing that behavior to include all items, and then apply the stricter filter in the `onMounted` hook of your component.

Regarding performance, I suggest lifting the definedness check for your filter out of the `filter`.
```ts
const selectedItems = computed(() => {
  if (!activeFilter.value) {
    return allItems
  }
  return allItems.filter((item) => item.topics?.includes(activeFilter.value))
})
```

**Comment by frederikheld** [comment]
Thanks for the quick and detailed reply!

Seems like I misunderstood the `ssr-columns` prop. I did not use it because I want the number of columns to adapt to the page width (which changes with breakpoints). But apparently this prop just defines what is being rendered into the html source code, but this will still be dynamically adapted according to `min-columns` and `max-columns`?

**Comment by DerYeger** [comment]
Yes, `ssr-columns` is only for the SSR render. There's no width data available during that phase, so no breakpoints-like behavior is possible.

On the client, the component will then update the layout after being mounted.

**Comment by frederikheld** [comment]
Sweet, thanks a lot for your support! It works like a charm now :-)

**Comment by DerYeger** [comment]
You're welcome!
