### ISSUE TITLE
feat(vite-plugin-lib): custom `tsconfig.json` name

### ISSUE THREAD

**Issue by ryanbas21** [DerYeger/yeger#180]
### Affected Packages

- [ ] @yeger/eslint-config
- [ ] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

Would you accept adding an option to pass in the tsconfig name? In certain setups `tsconfig.json` isn't always the name i.e. Nx monorepos use tsconfig.lib.json or tsconfig.base.json (where the paths live and base url live).

### Additional context

Nx monorepos by convention use tsconfig.base.json in the root of the workspace and libraries conventionally extend that config.

The typescript configuration looks like this
```
/
tsconfig.base.json
libs
  my-lib
     tsconfig.json -> extends tsconfig.base.json
     tsconfig.lib.json -> extends ./tsconfig.json
     tsconfig.spec.json -> extends ./tsconfig.json
```

I think we would just need to add `tsconfig` as a property to the Options interface

https://github.com/DerYeger/yeger/blob/main/packages/vite-plugin-lib/src/index.ts#L41 pass in `tsconfig` as a property to the arguments object, and it could remain defaulted to tsconfig.json

and pass in options into here https://github.com/DerYeger/yeger/blob/main/packages/vite-plugin-lib/src/index.ts#L198

I know this is an opinionated library so i do understand hesitation in configuring this value but it would open up a lot of compatibility for those who need the ts aliases to work where they arent in the dts plugin oob.

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
See https://github.com/DerYeger/yeger/pull/181#issuecomment-1663918734
