### ISSUE TITLE
feat: can u add a data push

### ISSUE THREAD

**Issue by AAAAAAAAAdai** [DerYeger/yeger#184]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

Hi, I have been using this plugin for some time now, but I have encountered some issues at work. I have noticed that on infinite scroll pages, the entire page is being re-rendered every time. Is it possible to add a data push feature to the plugin to avoid having to re-render all elements every time?

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
I don't think this is achievable while using the `items` prop as the single source of truth (which is required by the ability to remove elements).

**Comment by AAAAAAAAAdai** [comment]
> I don't think this is achievable while using the `items` prop as the single source of truth (which is required by the ability to remove elements).

I noticed that this project (https://github.com/fuxingloh/vue-masonry-wall) ↗) uses push to update data.

**Comment by DerYeger** [comment]
Yes, but it does not support removing elements.
