### ISSUE TITLE
[Question]: vue-masonry-wall keyMapper, generics stopped working on v4

### ISSUE THREAD

**Issue by FranciscoKloganB** [DerYeger/yeger#187]
### Description

Ever since `vue-masonry-wall` was integrated with `vue-masonry-wall-core`, and `keyMapper` started expecting a `KeyMapper<T>`, my generics stoped working. Do not know if this is a bug, or if I am doing something wrong.

## ShopList component (consumer)

```vue
<script setup lang="ts">
import { IProductListing } from './shop.types'

defineProps<{
  items: Array<IProductListing>
}>()
</script>

<template>
  <div>
    <AppGrid :items="items" :id-getter="(item) => item.prepr.id">
      <template #default="slotProps">
        <ShopListItem :item="slotProps.item" />
      </template>
    </AppGrid>
  </div>
</template>
```

## AppGrid component (can be a `grid` implementation or a wrapper around yeger's `masonry-wall`, depending on `variant`)

```vue
<script setup lang="ts" generic="T">
withDefaults(
  defineProps<{
    idGetter: (item: T) => string
    items: T[]
    showLoading?: boolean
    variant?: 'grid' | 'masonry'
  }>(),
  {
    showLoading: false,
    variant: 'grid',
  }
)

/** Allow consumers of AppGrid to access `slotProps.item` typing the item as T */
defineSlots<{
  default?: (props: { item: T }) => any
}>()
</script>

<template>
  <div :aria-label="$t('others.photographs-wall')" :class="[`app-${variant}`]">
    <template v-if="variant === 'grid'">
      <!-- Works as expected, type is correctly inferred -->
      <div v-for="item in items" :key="idGetter(item)">
        <slot :item="item" />
      </div>
    </template>
    <template v-else-if="variant === 'masonry'">
      <!-- Type is `(item: T) => string` not assignable to type `KeyMapper<unknown>` .-->
      <!--   Types of parameters `item` and `item` are incompatible -->
      <masonry-wall :items="items" :column-width="300" :gap="4" :key-mapper="idGetter">
        <template #default="slotProps">
          <!-- Type 'unknown' is not assignable to type 'T'. -->
          <slot :item="slotProps.item" />
        </template>
      </masonry-wall>
    </template>
  </div>
  <IconMdi:loading v-if="showLoading" class="animate-spin" />
</template>
```

The type errors around `Masonry Wall`, do not work even if I make `idGetter` a `(item: T, column: number, row: number, index: number) => number | string | symbol | undefined` nor even if I install `vue-masonry-wall-core` myself as a `devDependency`, import `KeyMapper` and mark it as `KeyMapper<T>`. When using either of these two approaches, my consumers (e.g.: `ShopList`), still get types properly inferred, but the masonry props still break.

### Additional context

My current solution to this problem is to

```vue
      <masonry-wall
        :items="items"
        :column-width="300"
        :gap="4"
        :key-mapper="(item) => idGetter(item as T)"
      >
        <template #default="slotProps">
          <slot :item="(slotProps.item as T)" />
        </template>
      </masonry-wall>
```

This also happens if I use `masonry-wall` directly of consumers instead of going through the wrapper

```vue
<script setup lang="ts">
import type { AlbumImage } from './album.types'

defineProps<{ items: Array<AlbumImage> }>()
</script>

<template>
  <!-- 'item' is of type 'unknown' -->
  <masonry-wall
    :items="items"
    :ssr-columns="1"
    :column-width="300"
    :gap="16"
    :key-mapper="(item) => item._id"
  >
    <template #default="{ item }">
      <PortfolioAlbumListItem :item="item" />
    </template>
  </masonry-wall>
</template>
```

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Thanks for the report, it should be fixed in v4.1.0!

Until v4, the generated types were broken due to an issue with vite-plugin-dts, resulting in the props accepting `any`.
v4 fixed that, but did not yet use the generic components of Vue 3.3.

This should now be enabled and correctly type the `keyMapper` again.
Further, the slot's  `item` should now also be correctly typed.
