### ISSUE TITLE
bug: Volar: Object literal may only specify known properties, and '"column-width"' does not exist in type

### ISSUE THREAD

**Issue by MartinX3** [DerYeger/yeger#190]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall 4.1.0
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

Volar claims "column-width" does not exist.

### Reproduction

```
<masonry-wall :column-width="280" :gap="16" :items="item">
	<template #default="{ index }">
		Placeholder
	</template>
</masonry-wall>
```

### Additional context

If I remove the `colum-width` it doesn't know the next attribute.
I use IntelliJ 2023.1.4 with Volar 1.6.5

```
Volar: Argument of type '{ columnWidth: number; "column-width": number; gap: number; items: GalleryEntry[]; }' is not assignable to parameter of type '{ columnWidth?: number | NonEmptyArray  | undefined; items: GalleryEntry[]; gap?: number | undefined; rtl?: boolean | undefined; ssrColumns?: number | undefined; scrollContainer?: HTMLElement | ... 1 more ... | undefined; minColumns?: number | undefined; maxColumns?: number | undefined; keyMapper?: KeyMapper...'. Object literal may only specify known properties, and '"column-width"' does not exist in type '{ columnWidth?: number | NonEmptyArray  | undefined; items: GalleryEntry[]; gap?: number | undefined; rtl?: boolean | undefined; ssrColumns?: number | undefined; scrollContainer?: HTMLElement | ... 1 more ... | undefined; minColumns?: number | undefined; maxColumns?: number | undefined; keyMapper?: KeyMapper...'.
```

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
I cannot reproduce this.
Are you using v4.1.0 of this package and Volar v1.8.5?

![CleanShot 2023-07-18 at 06 00 33@2x](https://github.com/DerYeger/yeger/assets/7950094/765d6980-602e-43ad-8155-20b8efba6a92)

**Comment by DerYeger** [comment]
Yes, this is an editor-specific issue. The `vue-tsc` CLI also works fine.

**Comment by MartinX3** [comment]
@DerYeger 
Now I use the newest Volar and the error disappeared.
But the autocompletion still doesn't work because volar doesn't find the type information for typescript.
The attributes are just marked as "Custom Vue component property" like also for the not existing properties as well.

**Comment by MartinX3** [comment]
I think the project misses type-/javascript docs or something like this to give me an autocompletion and description of the element properties like vue frameworks as vuetify or quasar give me in the IDE.

**Comment by DerYeger** [comment]
No, valid declaration files are included in the bundle. Feel free to check the `dist/types` directory as seen on https://www.npmjs.com/package/@yeger/vue-masonry-wall?activeTab=code.

The issue is with IntelliJ, as Volar has working autocomplete using VSCode.

**Comment by MartinX3** [comment]
Thank you.
I try my luck at their bug tracker.
https://youtrack.jetbrains.com/issue/WEB-62384/Autocompletion-for-node-modules-not-working-with-volar

**Comment by MartinX3** [comment]
I think the missing autocompletion is because IntelliJ wants the types as
https://github.com/JetBrains/web-types
https://plugins.jetbrains.com/docs/intellij/websymbols-web-types.html

And here the quasar support got added
https://github.com/quasarframework/quasar/pull/4749

Is there a way to generate them out of the `.d.ts` files?
