### ISSUE TITLE
bug: <TransitionGroup> children must be keyed

### ISSUE THREAD

**Issue by PierW** [DerYeger/yeger#195]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

I'm using vue-masonry-wall with TransitionGroup of Vue 3 because I need to add an animation each time that I delete or add a Card.
It doesn't works becouse TransitionGroup require that childs have an unique id, this is the the warning in console:
![Screenshot 2023-08-01 alle 18 46 09](https://github.com/DerYeger/yeger/assets/6259010/65f382f2-656f-4986-beb8-9971e688f8a2)

My code is like that:
`
          <TransitionGroup name="projects">

            <masonry-wall :items="projects" :gap="16">
              <template #default="{ item, index }">
                <div class="portfolio-item project">
                  <div v-if="currentFilter === item.category || currentFilter === 'ALL'" class="portfolio-wrap">
                    <img v-bind:src="item.image" class="img-fluid" :alt="item.title">
                    <div class="portfolio-info">
                      <h4>{{ item.title }}</h4>
                      <p>{{ item.category }}</p>
                      <div class="portfolio-links">
                        <a href="portfolio-details.html" class="portfolio-details-lightbox" title="Portfolio Details"><i class="bx bx-link"></i></a>
                      </div>
                    </div>
                  </div>
                </div>
              </template>
            </masonry-wall>

          </TransitionGroup>
`

How can I fix that and add the :key?

### Reproduction

Add masonry-wall component inside the TransitionGroup component

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
All elements of the masonry-wall are properly keyed.

While I don't have experience using `TransitionGroup`, its docs seem to imply that its immediate children need to use `v-for` and be keyed. Hence, you'll need to add a `:key` to `masonry-wall`. However, I don't think this will (or even is able to) animate the items of this library. That's just not how the transition group works.

**Comment by PierW** [comment]
I tried to use a "fake" :key with a Math.random(), it seems to fix that but I tried also other library, this is a common problem, so I fixed that building a "Masonry" effect with grid + TransitionGroup.
