### ISSUE TITLE
bug: Failed to resolve Vue import

### ISSUE THREAD

**Issue by Yizack** [DerYeger/yeger#209]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

I've just realized that the Vue import within the recent releases is being bundled with an absolute path that users can't access.

![image](https://github.com/DerYeger/yeger/assets/16264115/71844514-e974-46d8-b215-82e791d5bd18)

Error in console

![image](https://github.com/DerYeger/yeger/assets/16264115/99be7907-3ae7-4365-9fbe-a0410940fff3)

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-h4bzau

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Thanks for the report! I know what caused this issue and will push a fix later today.

As a memo for myself, the issue is caused by peer dependencies not being externalized by `vite-plugin-lib`.

**Comment by DerYeger** [comment]
@Yizack Please give v5.0.2 a try, it should be fixed.

**Comment by Yizack** [comment]
It's working perfectly!
