### ISSUE TITLE
[Question]: Your example clicked and reported an error

### ISSUE THREAD

**Issue by zzh948498** [DerYeger/yeger#240]
### Description

![image](https://github.com/DerYeger/yeger/assets/35091020/2869d74e-864f-4a10-8fe4-8b78470b4e7d)
https://vue-masonry-wall.yeger.eu/

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Thank you for the report!
Vue 3.3.10 somehow broke the props, so I downgraded the dependencies.
It should be fixed.
