### ISSUE TITLE
bug: Missing dist folder in Vue 2 package

### ISSUE THREAD

**Issue by wobsoriano** [DerYeger/yeger#249]
### Affected Packages

- [ ] @yeger/eslint-config
- [ ] @yeger/vue-masonry-wall
- [X] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

Missing `dist` folder in npm. Only in **5.0.4**.

![Screenshot 2024-01-15 at 2 14 40 PM](https://github.com/DerYeger/yeger/assets/13049130/199c83d1-a2d4-4aba-ab6d-fd675ce28d32)

### Reproduction

Go to https://www.npmjs.com/package/@yeger/vue2-masonry-wall?activeTab=code or install it locally and check for the missing `dist` folder

![Screenshot 2024-01-15 at 2 16 41 PM](https://github.com/DerYeger/yeger/assets/13049130/db94ccac-8ee1-44c2-af01-511e12ae06ce)

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by wobsoriano** [comment]
Also OT, do you have plans on supporting CJS build? 🗡️

**Comment by DerYeger** [comment]
Thanks for the report!
Something in the automated build pipeline must have gone wrong, but it's fixed now.

Regarding CJS, v4.2.1 and earlier include CJS builds. Since v5 I only ship ESM.
However, no features have been added since v4.2.1, so feel free to use that.

**Comment by wobsoriano** [comment]
Makes sense, thanks!
