### ISSUE TITLE
bug: rerender the view when using infinity scroll

### ISSUE THREAD

**Issue by AsgarovAsgar** [DerYeger/yeger#264]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

I use it in the Nuxt 3 app. When I load more data, it rerenders the view and jumps to the top of the page.
The scroll container is the window (default).

### Reproduction

I use Pinia, and new data is fetching when we reach the end of the page.
`res.data.results.forEach(image => {
      if(image.generated_image) {
        images.value = [...images.value, image]
      }
    })`
This is how I push new items to the array

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
I'm almost certain that the issue is caused by your image components having a height of `0` during their initial rendering.
You'll have to set their aspect ratio or find other measures to give them an initial height.

**Comment by AsgarovAsgar** [comment]
Yes, you are right. I put the aspect ratio using style binding, and then it worked. Thanks a lot

**Comment by xiaoxuwei12345** [comment]
<div
    class="infinite-scroll-container"
    v-infinite-scroll="loadMore"
    :infinite-scroll-disabled="infiniteScrollDisabled"
    infinite-scroll-distance="50">

        <MasonryWall :items="works" :ssr-columns="3" :max-columns="3" :column-width="128" :gap="20" >
          <template #default="{ item}" >
						<div>
							<img
							  :src="item.url"
							  style="width: 100%;height: auto;"
							/>						
						</div》
           </template>
        </MasonryWall>
  </div>


.infinite-scroll-container {
  height: 800px;
  overflow-x: auto;
  overflow-y: auto; 
}


Hello, I have encountered the same problem and I have set the aspect ratio, but it still doesn't work. Is there a problem with the code? Please give me more guidance, thank you!

**Comment by DerYeger** [comment]
> ```
>   <MasonryWall :items="works" :ssr-columns="3" :max-columns="3" :column-width="128" :gap="20" >
>     <template #default="{ item}" >
> 				<div>
> 					<img
> 					  :src="item.url"
> 					  style="width: 100%;height: auto;"
> 					/>						
> 				</div>
>      </template>
>   </MasonryWall>
> ```
> 
> .infinite-scroll-container { height: 800px; overflow-x: auto; overflow-y: auto; }
> 
> Hello, I have encountered the same problem(after loaded more data, it rerenders the view and jumps to the top of the page.) and I have set the aspect ratio, but it still doesn't work. Is there a problem with the code? Please give me more guidance, thank you!

No aspect ratio is being set in this example.
