### ISSUE TITLE
bug: when navigating from another page, page opens late

### ISSUE THREAD

**Issue by AsgarovAsgar** [DerYeger/yeger#268]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

When I visit the page from another page it navigates to that page late. It happens whenever I navigate to the page from another page. I changed MasonryWall with a standard div element, and it worked perfectly. As a default, I fetch 20 items, and when I change it to 3-4 items, it works well again. Here is the code for the page:

`
<script setup>
import { breakpointsTailwind, useBreakpoints } from '@vueuse/core'
const breakpoints = useBreakpoints(breakpointsTailwind)
const wallGap = ref(null)

const imageStore = useImageStore()
const { images, loading } = storeToRefs(imageStore)

function generateRandomHeights(numPlaceholders, minHeight, maxHeight) {
  const heights = [];
  for (let i = 0; i < numPlaceholders; i++) {
    const randomHeight = Math.floor(Math.random() * (maxHeight - minHeight + 1) + minHeight);
    heights.push(`${randomHeight}px`);
  }
  return heights;
}

onMounted(async () => {
  wallGap.value = breakpoints.isGreaterOrEqual('md') ? 12 : 4
  await imageStore.fetchImages()
})

</script>

<template>
  <div class="px-4 pt-2 md:p-8 md:pt-[5.5rem] mx-auto max-w-[1400px] flex flex-col h-screen gap-4 overscroll-none">
    
    <div class="flex flex-col gap-4">
      
      <MasonryWall v-if="loading" :items="generateRandomHeights(12, 200, 400)" :ssr-columns="6" min-columns="2" :column-width="250" :gap="wallGap">
        <template #default="{ item, index }">
          <div class="w-full bg-gray-300 rounded-xl" :style="{ height: item }"></div>
        </template>
      </MasonryWall>
      <MasonryWall v-if="!loading" :items="images" :ssr-columns="6" :column-width="250" min-columns="2" class="gap-2 md:gap-3" :gap="wallGap">
        <template #default="{ item, index }">
          <MasonryCard :image="item" :key="item.id" />
        </template>
      </MasonryWall>
      
    </div>
  </div>
</template>

`

### Reproduction

The problem does not happen on the laptop. When I start the dev server using 'npm run dev -- --host', and then open the app on my mobile phone, I see the problem. It happens in production on mobile phones as well.

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
This is not an issue of this component.

**Comment by AsgarovAsgar** [comment]
Hello. 
When I replace MasonryWall with a div element, it works as expected.
Did you manage to reproduce the problem that I faced?
Do you have any suggestions?

**Comment by DerYeger** [comment]
I won't reproduce your issue, please see https://antfu.me/posts/why-reproductions-are-required and consider creating a *minimal* reproduction.
