### ISSUE TITLE
bug: Duplicated items when `items` changes dynamically

### ISSUE THREAD

**Issue by dword-design** [DerYeger/yeger#294]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

When the `items` prop is a dynamic array which changes, there are duplicate items. Reason is probably that the [watcher](https://github.com/DerYeger/yeger/blob/009f923681769c1b48c0d563bb2567d35b753346/packages/vue-masonry-wall-core/src/index.ts#L185C10-L185C15) does not watch `() => props.items` but an array containing `items`. But `items` isn't necessarily a reactive variable. Storing the array in a computed property fixes the issue.

### Reproduction

Pass an array where new items are added depending on a variable.

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Watching an array of refs is valid reactivity, see https://vuejs.org/guide/essentials/watchers#watch-source-types.

[The docs of this library](https://github.com/DerYeger/yeger/tree/main/packages/vue-masonry-wall#adding-items) describe how to add items correctly.

**Comment by DerYeger** [comment]
> @DerYeger Yes but this only works if the vars watched in the array are reactive (ref, reactive, computed). A prop needs to be watched via a function call. See also [here](https://www.bacancytechnology.com/qanda/vue/watch-props-change-with-vue-composition-api-vue-3).

Indeed, hence `items` is a `ref` created via `toRefs(props)`.
I'm not using a `deep` watcher on purpose to prevent performance issues with large `items` arrays.

**Comment by DerYeger** [comment]
> hmmm ok I'm not sure if this is intended. If it's a decision I think it should be added to the docs since it's not obvious and contradicts to Vue intuition. I guess it's related to the comment about `push`.

Yes, it is intended and already mentioned [in the docs](https://github.com/DerYeger/yeger/tree/main/packages/vue-masonry-wall#adding-items): "_To add new items, assign a new value to the items property, e.g., items.value = [...items.value, newItem]. DO NOT push items to the array (e.g., items.value.push(newItem)), as such mutations will not be detected by the reactivity._"
