### ISSUE TITLE
bug: When the window is resized and the column count changes, all images are reloaded

### ISSUE THREAD

**Issue by dword-design** [DerYeger/yeger#297]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

When the window is resized and the column count changes, all images are reloaded. I think it would be good if the elements would still be there but rearranged. Otherwise the performance is poor on bigger resize events.

### Reproduction

Create a wall with multiple images and multiple columns. Then resize the window so that the column count changes.

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
This is not a bug, the slots are inherently stateless. You may either use a state-maintaining solution, e.g., stores, for your components, or ensure that a fresh mount won't result in UX issues, e.g., ensuring that the browser's built-in image caching is enabled.
