### ISSUE TITLE
bug: Child component state lost on column change

### ISSUE THREAD

**Issue by Wouter01** [DerYeger/yeger#30]
### Description

When the amount of columns is changed due to a window resize, the state of the children is lost. I suspect this is due to the way the grid is build since this just used the index as a key. I have done some research myself but wasn't able to fix it.

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Thank you for reporting this issue.

I think you're right, the issue is that changes in column count recreate every component. I can't think of a workaround right now, but I'm open for suggestions.

**Comment by sean-mllrdev** [comment]
Hello! Any updates on this?

**Comment by DerYeger** [comment]
> Hello! Any updates on this?

Unfortunately not, as I don't have time for OSS at the moment.

**Comment by lloyddayekh** [comment]
I'm having a weird issue on load some images look out of place but on window resize it stacks perfectly.
Any idea what might cause this?
Thank you

**Comment by DerYeger** [comment]
> I'm having a weird issue on load some images look out of place but on window resize it stacks perfectly.
> Any idea what might cause this?
> Thank you

See https://github.com/DerYeger/vue-masonry-wall#limitations.

**Comment by DerYeger** [comment]
Since I'm not aware of a workaround at this point, I'll close this issue as not planned.
Feel free to submit a PR if you know how to implement stable children.
