### ISSUE TITLE
bug: Not working Module not found: Error: Can't resolve '@yeger/vue-masonry-wall' 

### ISSUE THREAD

**Issue by rinatr1** [DerYeger/yeger#300]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [x] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

Module not found: Error: Can't resolve '@yeger/vue-masonry-wall' in '(..my_project_dir)\src'

main.js 
```
import MasonryWall from '@yeger/vue-masonry-wall';
```

package.json
```

    "@ntohq/buefy-next": "^0.1.2",
    "@yeger/vue-masonry-wall": "^5.0.12",
    "buefy": "github:buefy/buefy#buefy-next",
    "core-js": "^3.6.5",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "webpack": "^4.39.3"
```

### Reproduction

![изображение](https://github.com/DerYeger/yeger/assets/9809618/845964f3-160b-445f-8a2a-2ff28e1274a0)

### Additional context

Node version - v16.20.2

![изображение](https://github.com/DerYeger/yeger/assets/9809618/3147f0e1-e633-47c8-b9c7-e2bd4cd69435)

**Comment by DerYeger** [comment]
I need an actual reproduction to look into this, not just  a screenshot. My guess is that your build tool can’t handle modern ESM.
