### ISSUE TITLE
bug: potential item duplication

### ISSUE THREAD

**Issue by xiaoxuwei12345** [DerYeger/yeger#326]
### Affected Packages

- [ ] @yeger/eslint-config
- [ ] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

Hello! Thank you very much for your help recently. Now I have found a serious bug (please forgive me if I used it incorrectly). 

On mobile devices, if the Dimensions Responsive screen width is less than or equal to 449px, the server initially renders ssr-columns to 3 and max-columns to 3. When maxColumns is dynamically modified to 1 in js(Only modify maxColumns, not ssrColumns), each item will become repeated (that is, each item will be displayed twice). However, when the Dimensions Responsive screen width is greater than 449px, the above problem will not occur. You should be able to reproduce this error in Chrome's development environment.

Looking forward to your reply, thank you very much!

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Please create a [minimal reproduction](https://antfu.me/posts/why-reproductions-are-required), otherwise I'm not able to investigate any issues.

**Comment by xiaoxuwei12345** [comment]
Thanks for your reply! I don't have experience in creating a reproduction project on GitHub. Do I need to create a complete project (including pages and other directories, package.json, nuxt.config.ts.....)? Or do I only need to provide a test.vue file?

**Comment by DerYeger** [comment]
You don't need to create a full project (or even GitHub repository). Instead, you can use a tool like StackBlitz and

- add any required dependencies
- create a minimal implementation to reproduce the issue
- share the link.

See https://stackblitz.com/edit/vue3-vite-starter?file=README.md.

**Comment by DerYeger** [comment]
Thank you for the reproduction!
I was able to narrow it down to a race condition that happened tue to simoultaneous redraws caused by both your `onMounted` and the component's `onMounted` hooks.

v5.0.15 (for Vue 3) and v5.0.16 (for Vue 2) should fix the issue.
