### ISSUE TITLE
feat: fixed column count

### ISSUE THREAD

**Issue by DenFin** [DerYeger/yeger#66]
### Description

Hi @DerYeger,

firstly thanks for providing this plugin!

I am currently stuck with setting the correct column count. When I set `:ssr-columns="2"` I get the following layout

![Bildschirmfoto 2022-10-27 um 15 38 17](https://user-images.githubusercontent.com/11504119/198300202-3fa61d1b-5534-4b20-84f6-c1bcdca3324c.png)

Looking at the source code, it seems like the column count is dependent on the container/wall width.

```
function columnCount(): number {
  const count = Math.floor(
    (wall.value.getBoundingClientRect().width + gap.value) /
      (columnWidth.value + gap.value)
  )
  return count > 0 ? count : 1
}
```

### Solution

I think it would be nice to be able to set a columns count and the plugin calculates the width for the columns. So I can set a column count for a gallery, for example two, and no matter the width of the parent container or the wall, there always will be  2 columns.

I hope this makes sense.

### Additional context

In the above screenshot example I would like both gallerys to have 2 columns.

Similar to this layout:

![Bildschirmfoto 2022-10-27 um 15 52 59](https://user-images.githubusercontent.com/11504119/198303714-6906e742-8490-4383-8c61-abc2f9b88633.png)

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DenFin** [comment]
@DerYeger Hello again. I put some more thought into this. I think it would be even better if we could pass in a breakpoints object and define the columns count for different breakpoints. Similar to the API of SwiperJS for example

**Comment by DerYeger** [comment]
Hi @DenFin, thank you very much for the report.

The `ssr-columns` prop is only relevant for an initial (SSR) render.
Any client-side re-renders will not use it.

You're right, the column count only depends on the available width and the (minimum) `width` property.
I'm not sure if it makes sense to create a component that serves both use-cases (i.e., width based on count and count based on width).
It would probably be better to add a second component to this library, though I'm short on time for OSS at the moment.

**Comment by simonbrunel** [comment]
> @DerYeger  I'm not sure if it makes sense to create a component that serves both use-cases (i.e., width based on count and count based on width).

I would not expect another component and I'm pretty sure that picking the right options, it can work well with existing props. Another use case: be able to choose the maximum number of columns while keeping dynamic the number of columns.

We could add the following options:

- `max-columns: number`
- `min-columns: number`

It does not change the behavior of the component (still dynamic relying on `column-width`) but provides more control on the calculated number of columns. Thus, this library would fit more use cases such as the one mentioned above or @DenFin use case (i.e. `max-columns = min-columns`).

**Comment by DerYeger** [comment]
@simonbrunel This is a great suggestion, thanks!

**Comment by simonbrunel** [comment]
Awesome, thank you @DerYeger!
