### ISSUE TITLE
bug: vue2-masonry-wall on nuxt v2 

### ISSUE THREAD

**Issue by OndrejIT** [DerYeger/yeger#83]
### Description

Hello, I can't run vue2-masonry-wall on nuxt2

### Reproduction

Install @yeger/vue2-masonry-wall 2.3.0 on nuxt v2

### Additional context

Error:
`frontend-nuxt-1  |  WARN  Compiled with 7 warnings
frontend-nuxt-1  | 
frontend-nuxt-1  | 
frontend-nuxt-1  |  WARN  in ./node_modules/@yeger/vue2-masonry-wall/dist/masonry-wall.es.js
frontend-nuxt-1  | 
frontend-nuxt-1  | "export 'defineComponent' (imported as 'T') was not found in 'vue'
frontend-nuxt-1  | 
frontend-nuxt-1  | 
frontend-nuxt-1  |  WARN  in ./node_modules/@yeger/vue2-masonry-wall/dist/masonry-wall.es.js
frontend-nuxt-1  | 
frontend-nuxt-1  | "export 'nextTick' (imported as 'B') was not found in 'vue'
frontend-nuxt-1  | 
frontend-nuxt-1  | 
frontend-nuxt-1  |  WARN  in ./node_modules/@yeger/vue2-masonry-wall/dist/masonry-wall.es.js
frontend-nuxt-1  | 
frontend-nuxt-1  | "export 'onBeforeUnmount' (imported as 'b') was not found in 'vue'
frontend-nuxt-1  | 
frontend-nuxt-1  | 
frontend-nuxt-1  |  WARN  in ./node_modules/@yeger/vue2-masonry-wall/dist/masonry-wall.es.js
frontend-nuxt-1  | 
frontend-nuxt-1  | "export 'onMounted' (imported as 'k') was not found in 'vue'
frontend-nuxt-1  | 
frontend-nuxt-1  | 
frontend-nuxt-1  |  WARN  in ./node_modules/@yeger/vue2-masonry-wall/dist/masonry-wall.es.js
frontend-nuxt-1  | 
frontend-nuxt-1  | "export 'ref' (imported as 'y') was not found in 'vue'
frontend-nuxt-1  | 
frontend-nuxt-1  | 
frontend-nuxt-1  |  WARN  in ./node_modules/@yeger/vue2-masonry-wall/dist/masonry-wall.es.js
frontend-nuxt-1  | 
frontend-nuxt-1  | "export 'toRefs' (imported as '$') was not found in 'vue'
frontend-nuxt-1  | 
frontend-nuxt-1  | 
frontend-nuxt-1  |  WARN  in ./node_modules/@yeger/vue2-masonry-wall/dist/masonry-wall.es.js
frontend-nuxt-1  | 
frontend-nuxt-1  | "export 'watch' (imported as 'R') was not found in 'vue'
frontend-nuxt-1  | 
frontend-nuxt-1  | ℹ Waiting for file changes
frontend-nuxt-1  | ℹ Memory usage: 452 MB (RSS: 662 MB)
frontend-nuxt-1  | ℹ Listening on: http://172.21.0.8:3000/
`

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Thank you for the report!

Which Vue version are you using?
v.2.3.0 migrated to v2.7.14.
I'm not sure if there are backwards compatibility issues with Nuxt.

**Comment by DerYeger** [comment]
v2.3.1 now has the correct peer dependency of Vue `^2.7.0`.
Please try v2.2.0 if you're not using Vue v2.7.

**Comment by OndrejIT** [comment]
Thanks.
